### ISSUE TITLE
allocate reuse for loop partition

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#767] opened 2018-01-09 09:09 UTC
hi all,

for this case:
```
def test_parallel_alloc():
    ib = tvm.ir_builder.create()
    n = tvm.var("n")
    with ib.for_range(0, n, name="i") as i:
        with ib.for_range(0, 10, name="j") as j:
            A = ib.allocate("float32", 200, name="A", scope="local.L0A")
            A[j] = 1.2
        with ib.for_range(0, 10, name="j") as j:
            A = ib.allocate("float32", 200, name="A", scope="local.L0A")
            A[j] = 1.3

    body = ib.get()
    print(body)
    body = tvm.ir_pass.StorageRewrite(body)
    print(body)
```
now the first print is 
```
for (i, 0, n) {
  for (j, 0, 10) {
    // attr [A] storage_scope = "local.L0A"
    allocate A[float32 * 200]
    A[j] = 1.200000f
  }
  for (j, 0, 10) {
    // attr [A] storage_scope = "local.L0A"
    allocate A[float32 * 200]
    A[j] = 1.300000f
  }
}
```
the 2nd print
```
// attr [A] storage_scope = "local.L0A"
allocate A[float32 * 400]
for (i, 0, n) {
  for (j, 0, 10) {
    A[j] = 1.200000f
  }
  for (j, 0, 10) {
    A[(200 + j)] = 1.300000f
  }
}
```
Because it's the same space for A, so just allocate A[float32 * 200] is enough, can we do this in storage_rewrite pass?
this issue matters in loop partition, in which loop body will be duplicated, so that we will get two allocates point to the same space, and storage_rewrite will double it. if original allocate has been all the space of local.L0A, storage_rewrite will crash and reports,
`tvm._ffi.base.TVMError: [03:40:04] 
nnvm/tvm/src/pass/storage_rewrite.cc:605: Check failed: total_elem * e->elem_type.bits() <= info->max_num_bits (1048576 vs. 524288) Allocation exceed bound of memory tag local.L0A
  `

**Comment by xqdan** [comment] 2018-01-09 10:51
one way to solve this is inserting a storage_rewrite before loop partition

**Comment by kun-zh** [comment] 2018-01-09 15:53
Xiaoqiang, u mean we need to call StorageRewrite pass twice?

**Comment by tqchen** [comment] 2018-01-10 00:02
Should be fixed by https://github.com/dmlc/tvm/pull/770

Was caused by non-merge rule for local memory used in normal compiler(as they lower to register values)

**Comment by xqdan** [comment] 2018-01-10 01:19
thanks for quick fixing ^_^

**Closed** 2018-01-10 01:39 UTC
