### ISSUE TITLE
[TVM] [NNVM] Namespace pollution and name conflict of NodePtr

### ISSUE THREAD

**Issue by Anthony-Mai** [dmlc/tvm#2571] opened 2019-02-06 22:03 UTC
I notice there is a series name space pollution and name conflict issue, of NodePtr:
In [https://github.com/dmlc/tvm/blob/master/nnvm/include/nnvm/node.h#L29](url):
    using NodePtr = std::shared_ptr<Node>;
In [https://github.com/dmlc/tvm/blob/master/include/tvm/runtime/node_base.h#L95](url)
    template<typename T> class NodePtr {

The second definition, which defines NodePtr as a template class, is also duplicated in 
[3rdParty/HalideIR/src/tvm/node/node_base.h#L95](https://github.com/dmlc/HalideIR/blob/master/src/tvm/node/node_base.h#L95)

This is horrible and causes lots of confusion to the compiler and to any one reading the code, as it is unclear what exactly is NodePtr. I recommend:

1. Under nnvm, all NodePtr should be renamed, probably to Nodeptr, to avoid name conflict.
2. The "using" directive should never occur in a header file, as it causes name space pollution. Google would explicitly outlaw such usage, see Google C++ Style Guide for Namespaces: [https://google.github.io/styleguide/cppguide.html#Namespaces](url)

**Comment by Anthony-Mai** [comment] 2019-02-06 22:23
The Google C++ Sty;e Guide explicitly says:
- You may not use a using-directive to make all names from a namespace available.
- Do not use Namespace aliases at namespace scope in header files except in explicitly marked internal-only namespaces, because anything imported into a namespace in a header file becomes part of the public API exported by that file.

That means never to use "using namespace foo" in any *.h or *.cpp file, and never to use "using" directive in any header file. Always move such "using" directives to source files.

We don't necessarily have to follow all Google C++ style guide. But they came to that conclusion due to worry of namespace pollution, and the same reason is legitimate here as well. So it should be fixed.

**Comment by tqchen** [comment] 2019-02-07 00:24
Thanks for bringing it up, I understand the cause of the confusion, given that we are moving toward NNVMv2(relay), I think we will just leave the name as it is for now.

**Closed by tqchen** 2019-02-07 00:24 UTC
