### ISSUE TITLE
[Relay][Design] Why not import prelude when initializing module?

### ISSUE THREAD

**Issue by slyubomirsky** [dmlc/tvm#3366] opened 2019-06-13 22:16 UTC
Is there a reason the prelude is not loaded into the module upon initialization (maybe have a flag to disable the import if it's for some reason necessary)? It shouldn't lead to any overhead at run time since dead code elimination could take out any prelude functions that are not used anywhere in the program. It just seems like it would be a convenience.

@jroesch

**Comment by tqchen** [comment] 2019-06-13 22:20
Let us use https://discuss.tvm.ai/ for this kind of design questions, as the issue is not really actionable and cannot be closed in a definite amount of time

**Closed by tqchen** 2019-06-13 22:20 UTC
