### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when kernel_size is not specified

### ISSUE THREAD

**Issue by sf-wind** [dmlc/tvm#3666] opened 2019-07-30 17:33 UTC
the default value of "kernel_size" is None in relay.nn.conv2d. thus, when invoking the operator without specifying kernel_size, the code reports error:

TypeError: 'NoneType' object is not iterable

on: https://github.com/dmlc/tvm/blob/master/topi/python/topi/x86/conv2d.py#L437

Adding the kernel_size attribute to the operator get around the issue. 

Maybe should use https://github.com/dmlc/tvm/blob/master/topi/python/topi/x86/conv2d.py#L484 to get the kh and kw?

**Comment by cchung100m** [comment] 2019-08-04 09:07
Hi @sf-wind ,

Could you please demostrate the steps to reproduce this error, thanks.

**Comment by cchung100m** [comment] 2019-09-20 07:52
Hi @sf-wind @tqchen 

The `relay.nn.conv2d` has been updated a lot since this issue be reported and I think we don't have this issue currently.  Do we need this issue keep opening?

**Comment by tqchen** [comment] 2019-09-20 17:18
Close this issue for now, please bring followups to https://discuss.tvm.ai/

**Closed by tqchen** 2019-09-20 17:18 UTC
