### ISSUE TITLE
schedule is not normalized in InferRootBound (i.e., even after `normalize()` is called)

### ISSUE THREAD

**Issue by derisavi-huawei** [dmlc/tvm#756] opened 2018-01-05 18:37 UTC
Consider the following test case:
```python
import tvm
def test(dtype):
    M = 256
    N = 256
    A = tvm.placeholder((M, N), dtype, name = 'A')
    C = tvm.compute(
        (M, N),
        lambda x, y: (A[x, y]*4),
        name = 'C')

    s = tvm.create_schedule(C.op)

    subA = s.cache_read(A, "local", [C])
    subC = s.cache_write(C, "local")
    xo1, xo2 = s[C].split(s[C].op.axis[0], 2)
    xo3, xo4 = s[C].split(xo1, 2)

    s[subC].compute_at(s[C], xo3)
    s[subA].compute_at(s[C], xo3)

    xx, yy = s[subC].op.axis
    s[subC].bind(xx, tvm.thread_axis("threadIdx.x"))

    print(tvm.lower(s, [A, C], simple_mode=True))

test('float32')
```
When I run it, I get the following error message:
`src/schedule/bound.cc:131: Check failed: is_zero(vrange->min) InferBound requires every leaf iter var's min equals 0,  call schedule.normalize to achieve this. `
Note that this error happens in `InferBound()`->`InferRootBound()` which are called after `normalize()` in `tvm.lower()'.
Is this a valid test case? If yes, we need to understand why output of `normalize()` is not normalized.

**Comment by DengLLy** [comment] 2018-01-06 06:22
In normalize(), binded iter_var would not be rebased (see [here](https://github.com/dmlc/tvm/blob/master/src/schedule/schedule_dataflow_rewrite.cc#L248)). However, In this case, the iter axis was split before being binded, so InferBound() would return an error. 
If we call normalize() before binding the axis, we would face the problem as issue #733

**Comment by tqchen** [comment] 2018-01-06 20:24
since the range of the bound is dynamic depending on, there is a bit of ambiguity in this bind, as we are binding a dynamic ranged iter var([x, x+extent)) to a thread. We can do an explicit rebase on xx before bind, which might help solve the issue.

**Comment by DengLLy** [comment] 2018-01-10 05:57
Sorry I'm not totally understand what you meaning, @tqchen Is there another way to do an explicit rebase on xx? I think normalize() will cause other problems as I comment above.

**Comment by tqchen** [comment] 2018-01-10 06:25
I do mean explicitly do a rebase for this case

**Comment by tqchen** [comment] 2018-01-16 17:18
close for staleness. The issue is partially resolved by adopting the rebase approach

**Closed by tqchen** 2018-01-16 17:18 UTC

**Comment by derisavi-huawei** [comment] 2018-01-22 22:19
My understanding of the code is that in [lines 248-251 of schedule_dataflow_rewrite.cc](https://github.com/dmlc/tvm/blob/78e00410e5bdf5f4428e39285cac75592233a813/src/schedule/schedule_dataflow_rewrite.cc#L248) we avoid rebasing bound variables. What's the reason? What's the problem if we comment those lines?
FYI, When I comment those lines, the testcase above passes and all TVM's python tests pass, as well.

**Comment by tqchen** [comment] 2018-01-22 22:38
it is because the thread binding semantics of different scope is not very well defined in this case(are we bind to the rebased one, or the original one as the code indicated)
