### ISSUE TITLE
When I run  tutorial/get_started.py, some error occurs when producing CUDA device code..

### ISSUE THREAD

**Issue by limin2015** [dmlc/tvm#760] opened 2018-01-08 02:25 UTC
After installing tvm, I execute the example in tutorial/get_started.py, but it failed when build cuda code.
Worth noting is that 
(1)Other examples for producing cpu code is right.
(2)I compile by adding "USE_CUDA = 1 and designating CUDA_PATH". (with cuda-8.0) 

The errors are as follows:

RUN: python get_started.py
 
OUTPUT:

<class 'tvm.tensor.Tensor'>
Traceback (most recent call last):
  File "get_started.py", line 111, in <module>
    fadd_cuda = tvm.build(s, [A, B, C], "cuda", target_host="llvm", name="myadd")
  File "/**/tvm/python/tvm/build_module.py", line 364, in build
    mdev = codegen.build_module(fdevice, str(target_device))
  File "/**/tvm/python/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/**/tvm/python/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/**/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/**/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [18:14:07] src/codegen/codegen.cc:27: Check failed: bf != nullptr Target cuda is not enabled

**Comment by tqchen** [comment] 2018-01-08 19:48
Make sure you rebuilt TVM with cuda enabled(do make clean and make) and reinstall the tvm

**Comment by limin2015** [comment] 2018-01-09 02:04
It still doesn't work.

**Comment by tqchen** [comment] 2018-01-09 03:14
You will have to check if by yourself then, basically this is caused by https://github.com/dmlc/tvm/blob/master/src/codegen/build_cuda.cc#L76 not being registered or linked to your tvm library

**Comment by limin2015** [comment] 2018-01-09 03:29
Ok . Thanks for your help. And another error information is added when I run get_started.py after make again:

<class 'tvm.tensor.Tensor'>
[19:26:17] src/pass/loop_partition.cc:345: Cannot prove: (((((63 + n)/64) - 1) - ((((n - 1) - 63)/64) + 1)) >= 0), when generating the post doubt loop

**Comment by tqchen** [comment] 2018-01-09 03:58
this was an issue that should be fixed by master already in a recently merged PR #755

**Closed by tqchen** 2018-01-09 03:58 UTC

**Comment by feiyuvl** [comment] 2018-05-09 06:06
@tqchen I write a special batch-gemm and get the same problem when using the latest tvm. If I set the matrix size (m, n) to a const, it will be ok,  however if I let `m = tvm.var('m')`, it occurs the error
![default](https://user-images.githubusercontent.com/13388702/39798180-fe2d8d9a-5391-11e8-90b3-9764b6363001.PNG)

**Comment by feiyuvl** [comment] 2018-05-09 06:57
@tqchen Sorry, the real error occurs in `src/pass/storage_sync.cc:76`, following is the full stack
![default](https://user-images.githubusercontent.com/13388702/39800002-ea3edefe-5398-11e8-9593-a6e33ca9c6ec.PNG)
It seems the shared memory load pass causes the error. Any help will be appreciated
