### ISSUE TITLE
memory leak of tvm

### ISSUE THREAD

**Issue by xqdan** [dmlc/tvm#824] opened 2018-01-25 10:42 UTC
```
nnvm/tvm/dmlc-core/src/data.cc:31,error,memleak,Memory leak: parser

nnvm/tvm/dmlc-core/src/data.cc:46,error,memleak,Memory leak: parser

nnvm/tvm/src/codegen/llvm/codegen_cpu.cc:122,error,memleak,Memory leak: global
```

**Comment by PENGUINLIONG** [comment] 2018-01-25 15:16
```
nnvm/tvm/src/codegen/llvm/codegen_cpu.cc:122,error,memleak,Memory leak: global
```
This seems not a bug. The GlobalVariable instance will be appended to the global list.
See the implementation of [GlobalVariable](http://llvm.org/doxygen/Globals_8cpp_source.html#l00307).

**Comment by PENGUINLIONG** [comment] 2018-01-25 15:26
```
nnvm/tvm/dmlc-core/src/data.cc:31,error,memleak,Memory leak: parser
nnvm/tvm/dmlc-core/src/data.cc:46,error,memleak,Memory leak: parser
```
These two seems working properly either. Newed `parser`s are [received](https://github.com/dmlc/dmlc-core/blob/bf321638b22d1d33bb36775e925f7b43b22db688/src/data/parser.h#L74) by `ThreadedParser`, and are properly released in [dtor](https://github.com/dmlc/dmlc-core/blob/bf321638b22d1d33bb36775e925f7b43b22db688/src/data/parser.h#L86). Not sure what does the memleak checker complain about.

**Closed** 2018-01-26 02:52 UTC
